# Generated by Django 4.2.2 on 2023-07-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_client_birthday_alter_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=10)),
                ('barcode', models.IntegerField(unique=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_registred', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.product')),
            ],
        ),
    ]
